version: "3.9"

services:
  backend:
    build:
      context: ./fastapi-backend
      dockerfile: Dockerfile
    container_name: money-heist-ctf-1-backend-1
    env_file:
      - ./fastapi-backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - redis
      - opensearch
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: money-heist-ctf-1-frontend-1
    ports:
      - "80:80"         # frontend now on http://localhost
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: money-heist-ctf-1-redis-1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mariadb:
    image: mariadb:10.6
    container_name: money-heist-ctf-1-mariadb-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: money_heist
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  opensearch:
    image: opensearchproject/opensearch:2.10.0
    container_name: money-heist-ctf-1-opensearch-1
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  minio:
    image: minio/minio
    container_name: money-heist-ctf-1-minio-1
    command: server /data --console-address ":42155"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"     # S3 API
      - "42155:42155"   # Console/UI (fixes random host port)
    volumes:
      - minio_data:/data

  grafana:
    image: grafana/grafana:9.5.0
    container_name: money-heist-ctf-1-grafana-1
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - mariadb

  metabase:
    image: metabase/metabase:latest
    container_name: money-heist-ctf-1-metabase-1
    ports:
      - "3001:3000"

volumes:
  mariadb_data:
  redis_data:
  opensearch_data:
  grafana_data:
  minio_data:
